// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.28.2
// source: dynamic_consumer.proto

package api

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConsumerPushDynamicReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title    string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Info     string   `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	ImageUrl []string `protobuf:"bytes,5,rep,name=ImageUrl,proto3" json:"ImageUrl,omitempty"`
}

func (x *ConsumerPushDynamicReq) Reset() {
	*x = ConsumerPushDynamicReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_consumer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsumerPushDynamicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerPushDynamicReq) ProtoMessage() {}

func (x *ConsumerPushDynamicReq) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_consumer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerPushDynamicReq.ProtoReflect.Descriptor instead.
func (*ConsumerPushDynamicReq) Descriptor() ([]byte, []int) {
	return file_dynamic_consumer_proto_rawDescGZIP(), []int{0}
}

func (x *ConsumerPushDynamicReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ConsumerPushDynamicReq) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *ConsumerPushDynamicReq) GetImageUrl() []string {
	if x != nil {
		return x.ImageUrl
	}
	return nil
}

type ConsumerPushDynamicReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg  string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ConsumerPushDynamicReply) Reset() {
	*x = ConsumerPushDynamicReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_consumer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConsumerPushDynamicReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumerPushDynamicReply) ProtoMessage() {}

func (x *ConsumerPushDynamicReply) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_consumer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumerPushDynamicReply.ProtoReflect.Descriptor instead.
func (*ConsumerPushDynamicReply) Descriptor() ([]byte, []int) {
	return file_dynamic_consumer_proto_rawDescGZIP(), []int{1}
}

func (x *ConsumerPushDynamicReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ConsumerPushDynamicReply) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_dynamic_consumer_proto protoreflect.FileDescriptor

var file_dynamic_consumer_proto_rawDesc = []byte{
	0x0a, 0x16, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69,
	0x63, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x22, 0x5e, 0x0a, 0x16, 0x43, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x72, 0x50, 0x75, 0x73, 0x68, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a,
	0x08, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x08, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x40, 0x0a, 0x18, 0x43, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x72, 0x50, 0x75, 0x73, 0x68, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x32, 0x6d, 0x0a, 0x08, 0x43,
	0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x12, 0x61, 0x0a, 0x0b, 0x50, 0x75, 0x73, 0x68, 0x44,
	0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x12, 0x27, 0x2e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x72, 0x50, 0x75, 0x73, 0x68, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x71, 0x1a,
	0x29, 0x2e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65,
	0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x50, 0x75, 0x73, 0x68, 0x44, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c, 0x69, 0x75, 0x68, 0x75, 0x61, 0x31,
	0x33, 0x30, 0x37, 0x2f, 0x49, 0x6d, 0x47, 0x6f, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x64, 0x79, 0x6e,
	0x61, 0x6d, 0x69, 0x63, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x72, 0x2f, 0x6b, 0x69,
	0x74, 0x65, 0x78, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_dynamic_consumer_proto_rawDescOnce sync.Once
	file_dynamic_consumer_proto_rawDescData = file_dynamic_consumer_proto_rawDesc
)

func file_dynamic_consumer_proto_rawDescGZIP() []byte {
	file_dynamic_consumer_proto_rawDescOnce.Do(func() {
		file_dynamic_consumer_proto_rawDescData = protoimpl.X.CompressGZIP(file_dynamic_consumer_proto_rawDescData)
	})
	return file_dynamic_consumer_proto_rawDescData
}

var file_dynamic_consumer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_dynamic_consumer_proto_goTypes = []interface{}{
	(*ConsumerPushDynamicReq)(nil),   // 0: DynamicConsumer.ConsumerPushDynamicReq
	(*ConsumerPushDynamicReply)(nil), // 1: DynamicConsumer.ConsumerPushDynamicReply
}
var file_dynamic_consumer_proto_depIdxs = []int32{
	0, // 0: DynamicConsumer.Consumer.PushDynamic:input_type -> DynamicConsumer.ConsumerPushDynamicReq
	1, // 1: DynamicConsumer.Consumer.PushDynamic:output_type -> DynamicConsumer.ConsumerPushDynamicReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dynamic_consumer_proto_init() }
func file_dynamic_consumer_proto_init() {
	if File_dynamic_consumer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dynamic_consumer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsumerPushDynamicReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_consumer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConsumerPushDynamicReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dynamic_consumer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dynamic_consumer_proto_goTypes,
		DependencyIndexes: file_dynamic_consumer_proto_depIdxs,
		MessageInfos:      file_dynamic_consumer_proto_msgTypes,
	}.Build()
	File_dynamic_consumer_proto = out.File
	file_dynamic_consumer_proto_rawDesc = nil
	file_dynamic_consumer_proto_goTypes = nil
	file_dynamic_consumer_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.11.3. DO NOT EDIT.

type Consumer interface {
	PushDynamic(ctx context.Context, req *ConsumerPushDynamicReq) (res *ConsumerPushDynamicReply, err error)
}
