// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.2
// source: dynamic_producer.proto

package api

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SpaceGetFocusDynamicReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetID uint64 `protobuf:"varint,1,opt,name=TargetID,proto3" json:"TargetID,omitempty"`
	Limit    int64  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
}

func (x *SpaceGetFocusDynamicReq) Reset() {
	*x = SpaceGetFocusDynamicReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceGetFocusDynamicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceGetFocusDynamicReq) ProtoMessage() {}

func (x *SpaceGetFocusDynamicReq) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceGetFocusDynamicReq.ProtoReflect.Descriptor instead.
func (*SpaceGetFocusDynamicReq) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{0}
}

func (x *SpaceGetFocusDynamicReq) GetTargetID() uint64 {
	if x != nil {
		return x.TargetID
	}
	return 0
}

func (x *SpaceGetFocusDynamicReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SpaceGetFocusDynamicReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dynamic []*Dynamic `protobuf:"bytes,1,rep,name=dynamic_producer,proto3" json:"dynamic_producer,omitempty"`
	Time    int64      `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
}

func (x *SpaceGetFocusDynamicReply) Reset() {
	*x = SpaceGetFocusDynamicReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpaceGetFocusDynamicReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpaceGetFocusDynamicReply) ProtoMessage() {}

func (x *SpaceGetFocusDynamicReply) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpaceGetFocusDynamicReply.ProtoReflect.Descriptor instead.
func (*SpaceGetFocusDynamicReply) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{1}
}

func (x *SpaceGetFocusDynamicReply) GetDynamic() []*Dynamic {
	if x != nil {
		return x.Dynamic
	}
	return nil
}

func (x *SpaceGetFocusDynamicReply) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type Dynamic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID          uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	AuthorId    uint64   `protobuf:"varint,2,opt,name=AuthorId,proto3" json:"AuthorId,omitempty"`
	Title       string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Info        string   `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	ImageUrl    []string `protobuf:"bytes,5,rep,name=ImageUrl,proto3" json:"ImageUrl,omitempty"`
	CommentList []uint64 `protobuf:"varint,6,rep,packed,name=commentList,proto3" json:"commentList,omitempty"`
}

func (x *Dynamic) Reset() {
	*x = Dynamic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Dynamic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dynamic) ProtoMessage() {}

func (x *Dynamic) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dynamic.ProtoReflect.Descriptor instead.
func (*Dynamic) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{2}
}

func (x *Dynamic) GetID() uint64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Dynamic) GetAuthorId() uint64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *Dynamic) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Dynamic) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *Dynamic) GetImageUrl() []string {
	if x != nil {
		return x.ImageUrl
	}
	return nil
}

func (x *Dynamic) GetCommentList() []uint64 {
	if x != nil {
		return x.CommentList
	}
	return nil
}

type SpacePushDynamicReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title    string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Info     string   `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	ImageUrl []string `protobuf:"bytes,5,rep,name=ImageUrl,proto3" json:"ImageUrl,omitempty"`
}

func (x *SpacePushDynamicReq) Reset() {
	*x = SpacePushDynamicReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpacePushDynamicReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpacePushDynamicReq) ProtoMessage() {}

func (x *SpacePushDynamicReq) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpacePushDynamicReq.ProtoReflect.Descriptor instead.
func (*SpacePushDynamicReq) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{3}
}

func (x *SpacePushDynamicReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SpacePushDynamicReq) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *SpacePushDynamicReq) GetImageUrl() []string {
	if x != nil {
		return x.ImageUrl
	}
	return nil
}

type SpacePushDynamicReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg  string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *SpacePushDynamicReply) Reset() {
	*x = SpacePushDynamicReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_space_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SpacePushDynamicReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpacePushDynamicReply) ProtoMessage() {}

func (x *SpacePushDynamicReply) ProtoReflect() protoreflect.Message {
	mi := &file_space_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpacePushDynamicReply.ProtoReflect.Descriptor instead.
func (*SpacePushDynamicReply) Descriptor() ([]byte, []int) {
	return file_space_proto_rawDescGZIP(), []int{4}
}

func (x *SpacePushDynamicReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SpacePushDynamicReply) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_space_proto protoreflect.FileDescriptor

var file_space_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x22, 0x4b, 0x0a, 0x17, 0x53, 0x70, 0x61, 0x63, 0x65, 0x47, 0x65, 0x74,
	0x46, 0x6f, 0x63, 0x75, 0x73, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x71, 0x12,
	0x1a, 0x0a, 0x08, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x22, 0x59, 0x0a, 0x19, 0x53, 0x70, 0x61, 0x63, 0x65, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x63,
	0x75, 0x73, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x28,
	0x0a, 0x07, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52,
	0x07, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x9d, 0x01, 0x0a,
	0x07, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x41, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x1a,
	0x0a, 0x08, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x08, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x06, 0x20, 0x03, 0x28, 0x04, 0x52,
	0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x5b, 0x0a, 0x13,
	0x53, 0x70, 0x61, 0x63, 0x65, 0x50, 0x75, 0x73, 0x68, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63,
	0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a,
	0x08, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x08, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x55, 0x72, 0x6c, 0x22, 0x3d, 0x0a, 0x15, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x50, 0x75, 0x73, 0x68, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x32, 0xa5, 0x01, 0x0a, 0x05, 0x53, 0x70, 0x61,
	0x63, 0x65, 0x12, 0x53, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x44, 0x79,
	0x6e, 0x61, 0x6d, 0x69, 0x63, 0x12, 0x1e, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x44, 0x79, 0x6e, 0x61, 0x6d,
	0x69, 0x63, 0x52, 0x65, 0x71, 0x1a, 0x20, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x53, 0x70,
	0x61, 0x63, 0x65, 0x47, 0x65, 0x74, 0x46, 0x6f, 0x63, 0x75, 0x73, 0x44, 0x79, 0x6e, 0x61, 0x6d,
	0x69, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x47, 0x0a, 0x0b, 0x50, 0x75, 0x73, 0x68, 0x44,
	0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x12, 0x1a, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x53,
	0x70, 0x61, 0x63, 0x65, 0x50, 0x75, 0x73, 0x68, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52,
	0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x50, 0x75, 0x73, 0x68, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6c,
	0x69, 0x75, 0x68, 0x75, 0x61, 0x31, 0x33, 0x30, 0x37, 0x2f, 0x49, 0x6d, 0x47, 0x6f, 0x2f, 0x72,
	0x70, 0x63, 0x2f, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f, 0x67,
	0x65, 0x6e, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_space_proto_rawDescOnce sync.Once
	file_space_proto_rawDescData = file_space_proto_rawDesc
)

func file_space_proto_rawDescGZIP() []byte {
	file_space_proto_rawDescOnce.Do(func() {
		file_space_proto_rawDescData = protoimpl.X.CompressGZIP(file_space_proto_rawDescData)
	})
	return file_space_proto_rawDescData
}

var file_space_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_space_proto_goTypes = []interface{}{
	(*SpaceGetFocusDynamicReq)(nil),   // 0: dynamic_producer.SpaceGetFocusDynamicReq
	(*SpaceGetFocusDynamicReply)(nil), // 1: dynamic_producer.SpaceGetFocusDynamicReply
	(*Dynamic)(nil),                   // 2: dynamic_producer.Dynamic
	(*SpacePushDynamicReq)(nil),       // 3: dynamic_producer.SpacePushDynamicReq
	(*SpacePushDynamicReply)(nil),     // 4: dynamic_producer.SpacePushDynamicReply
}
var file_space_proto_depIdxs = []int32{
	2, // 0: dynamic_producer.SpaceGetFocusDynamicReply.dynamic_producer:type_name -> dynamic_producer.Dynamic
	0, // 1: dynamic_producer.Space.GetFocusDynamic:input_type -> dynamic_producer.SpaceGetFocusDynamicReq
	3, // 2: dynamic_producer.Space.PushDynamic:input_type -> dynamic_producer.SpacePushDynamicReq
	1, // 3: dynamic_producer.Space.GetFocusDynamic:output_type -> dynamic_producer.SpaceGetFocusDynamicReply
	4, // 4: dynamic_producer.Space.PushDynamic:output_type -> dynamic_producer.SpacePushDynamicReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_space_proto_init() }
func file_space_proto_init() {
	if File_space_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_space_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceGetFocusDynamicReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpaceGetFocusDynamicReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Dynamic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpacePushDynamicReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_space_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SpacePushDynamicReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_space_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_space_proto_goTypes,
		DependencyIndexes: file_space_proto_depIdxs,
		MessageInfos:      file_space_proto_msgTypes,
	}.Build()
	File_space_proto = out.File
	file_space_proto_rawDesc = nil
	file_space_proto_goTypes = nil
	file_space_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.10.3. DO NOT EDIT.

type Space interface {
	GetFocusDynamic(ctx context.Context, req *SpaceGetFocusDynamicReq) (res *SpaceGetFocusDynamicReply, err error)
	PushDynamic(ctx context.Context, req *SpacePushDynamicReq) (res *SpacePushDynamicReply, err error)
}
