// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/cloudwego/kitex/server"
	"github.com/liuhua1307/ImGo/rpc/dynamics/dynamic_producer/configs"
	"github.com/liuhua1307/ImGo/rpc/dynamics/dynamic_producer/pkg/cache"
	"github.com/liuhua1307/ImGo/rpc/dynamics/dynamic_producer/pkg/mq"
	cache2 "github.com/liuhua1307/ImGo/rpc/dynamics/dynamic_producer/producer/cache"
	"github.com/liuhua1307/ImGo/rpc/dynamics/dynamic_producer/producer/repository"
	"github.com/liuhua1307/ImGo/rpc/dynamics/dynamic_producer/producer/usecase"
	server2 "github.com/liuhua1307/ImGo/rpc/dynamics/dynamic_producer/server"
)

// Injectors from wire.go:

func wireApp() server.Server {
	context := configs.NewContext()
	client := configs.NewRDB(context)
	redisCache := cache.NewRedis(client)
	db := configs.DB(context)
	dynamicsMYSQLRepository := repository.NewDynamicsMYSQLRepository(db)
	producer := configs.NewProducer()
	rocket := mq.NewRocket(producer)
	mqMq := mq.NewMQ(rocket)
	dynamicsRedisRepository := cache2.NewDynamicsRepository(redisCache, dynamicsMYSQLRepository, mqMq)
	dynamicUseCase := usecase.NewDynamicsUseCase(dynamicsRedisRepository)
	space := server2.NewSpaceImpl(dynamicUseCase)
	serverServer := server2.NewKitexServer(space)
	return serverServer
}
