// Code generated by Kitex v0.10.3. DO NOT EDIT.

package sms

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	api "github.com/liuhua1307/ImGo/rpc/sms/kitex_gen/api"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for domain method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetSMSCode": kitex.NewMethodInfo(
		getSMSCodeHandler,
		newGetSMSCodeArgs,
		newGetSMSCodeResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	smsServiceInfo                = NewServiceInfo()
	smsServiceInfoForClient       = NewServiceInfoForClient()
	smsServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return smsServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return smsServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return smsServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Sms"
	handlerType := (*api.Sms)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "sms",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.10.3",
		Extra:           extra,
	}
	return svcInfo
}

func getSMSCodeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(api.SmsGetCodeReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(api.Sms).GetSMSCode(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetSMSCodeArgs:
		success, err := handler.(api.Sms).GetSMSCode(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetSMSCodeResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetSMSCodeArgs() interface{} {
	return &GetSMSCodeArgs{}
}

func newGetSMSCodeResult() interface{} {
	return &GetSMSCodeResult{}
}

type GetSMSCodeArgs struct {
	Req *api.SmsGetCodeReq
}

func (p *GetSMSCodeArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(api.SmsGetCodeReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetSMSCodeArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetSMSCodeArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetSMSCodeArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetSMSCodeArgs) Unmarshal(in []byte) error {
	msg := new(api.SmsGetCodeReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetSMSCodeArgs_Req_DEFAULT *api.SmsGetCodeReq

func (p *GetSMSCodeArgs) GetReq() *api.SmsGetCodeReq {
	if !p.IsSetReq() {
		return GetSMSCodeArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetSMSCodeArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetSMSCodeArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetSMSCodeResult struct {
	Success *api.SmsGetCodeReply
}

var GetSMSCodeResult_Success_DEFAULT *api.SmsGetCodeReply

func (p *GetSMSCodeResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(api.SmsGetCodeReply)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetSMSCodeResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetSMSCodeResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetSMSCodeResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetSMSCodeResult) Unmarshal(in []byte) error {
	msg := new(api.SmsGetCodeReply)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetSMSCodeResult) GetSuccess() *api.SmsGetCodeReply {
	if !p.IsSetSuccess() {
		return GetSMSCodeResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetSMSCodeResult) SetSuccess(x interface{}) {
	p.Success = x.(*api.SmsGetCodeReply)
}

func (p *GetSMSCodeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetSMSCodeResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetSMSCode(ctx context.Context, Req *api.SmsGetCodeReq) (r *api.SmsGetCodeReply, err error) {
	var _args GetSMSCodeArgs
	_args.Req = Req
	var _result GetSMSCodeResult
	if err = p.c.Call(ctx, "GetSMSCode", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
