// Code generated by Kitex v0.10.3. DO NOT EDIT.

package space

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	api "github.com/liuhua1307/ImGo/rpc/space/kitex_gen/api"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for domain method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"GetFocusDynamic": kitex.NewMethodInfo(
		getFocusDynamicHandler,
		newGetFocusDynamicArgs,
		newGetFocusDynamicResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
	"PushDynamic": kitex.NewMethodInfo(
		pushDynamicHandler,
		newPushDynamicArgs,
		newPushDynamicResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	spaceServiceInfo                = NewServiceInfo()
	spaceServiceInfoForClient       = NewServiceInfoForClient()
	spaceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return spaceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return spaceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return spaceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Space"
	handlerType := (*api.Space)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "space",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.10.3",
		Extra:           extra,
	}
	return svcInfo
}

func getFocusDynamicHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(api.SpaceGetFocusDynamicReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(api.Space).GetFocusDynamic(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *GetFocusDynamicArgs:
		success, err := handler.(api.Space).GetFocusDynamic(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetFocusDynamicResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newGetFocusDynamicArgs() interface{} {
	return &GetFocusDynamicArgs{}
}

func newGetFocusDynamicResult() interface{} {
	return &GetFocusDynamicResult{}
}

type GetFocusDynamicArgs struct {
	Req *api.SpaceGetFocusDynamicReq
}

func (p *GetFocusDynamicArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(api.SpaceGetFocusDynamicReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetFocusDynamicArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetFocusDynamicArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetFocusDynamicArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *GetFocusDynamicArgs) Unmarshal(in []byte) error {
	msg := new(api.SpaceGetFocusDynamicReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetFocusDynamicArgs_Req_DEFAULT *api.SpaceGetFocusDynamicReq

func (p *GetFocusDynamicArgs) GetReq() *api.SpaceGetFocusDynamicReq {
	if !p.IsSetReq() {
		return GetFocusDynamicArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetFocusDynamicArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *GetFocusDynamicArgs) GetFirstArgument() interface{} {
	return p.Req
}

type GetFocusDynamicResult struct {
	Success *api.SpaceGetFocusDynamicReply
}

var GetFocusDynamicResult_Success_DEFAULT *api.SpaceGetFocusDynamicReply

func (p *GetFocusDynamicResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(api.SpaceGetFocusDynamicReply)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetFocusDynamicResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetFocusDynamicResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetFocusDynamicResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *GetFocusDynamicResult) Unmarshal(in []byte) error {
	msg := new(api.SpaceGetFocusDynamicReply)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetFocusDynamicResult) GetSuccess() *api.SpaceGetFocusDynamicReply {
	if !p.IsSetSuccess() {
		return GetFocusDynamicResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetFocusDynamicResult) SetSuccess(x interface{}) {
	p.Success = x.(*api.SpaceGetFocusDynamicReply)
}

func (p *GetFocusDynamicResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *GetFocusDynamicResult) GetResult() interface{} {
	return p.Success
}

func pushDynamicHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(api.SpacePushDynamicReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(api.Space).PushDynamic(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *PushDynamicArgs:
		success, err := handler.(api.Space).PushDynamic(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*PushDynamicResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newPushDynamicArgs() interface{} {
	return &PushDynamicArgs{}
}

func newPushDynamicResult() interface{} {
	return &PushDynamicResult{}
}

type PushDynamicArgs struct {
	Req *api.SpacePushDynamicReq
}

func (p *PushDynamicArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(api.SpacePushDynamicReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *PushDynamicArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *PushDynamicArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *PushDynamicArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *PushDynamicArgs) Unmarshal(in []byte) error {
	msg := new(api.SpacePushDynamicReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var PushDynamicArgs_Req_DEFAULT *api.SpacePushDynamicReq

func (p *PushDynamicArgs) GetReq() *api.SpacePushDynamicReq {
	if !p.IsSetReq() {
		return PushDynamicArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *PushDynamicArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PushDynamicArgs) GetFirstArgument() interface{} {
	return p.Req
}

type PushDynamicResult struct {
	Success *api.SpacePushDynamicReply
}

var PushDynamicResult_Success_DEFAULT *api.SpacePushDynamicReply

func (p *PushDynamicResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(api.SpacePushDynamicReply)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *PushDynamicResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *PushDynamicResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *PushDynamicResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *PushDynamicResult) Unmarshal(in []byte) error {
	msg := new(api.SpacePushDynamicReply)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *PushDynamicResult) GetSuccess() *api.SpacePushDynamicReply {
	if !p.IsSetSuccess() {
		return PushDynamicResult_Success_DEFAULT
	}
	return p.Success
}

func (p *PushDynamicResult) SetSuccess(x interface{}) {
	p.Success = x.(*api.SpacePushDynamicReply)
}

func (p *PushDynamicResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PushDynamicResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) GetFocusDynamic(ctx context.Context, Req *api.SpaceGetFocusDynamicReq) (r *api.SpaceGetFocusDynamicReply, err error) {
	var _args GetFocusDynamicArgs
	_args.Req = Req
	var _result GetFocusDynamicResult
	if err = p.c.Call(ctx, "GetFocusDynamic", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) PushDynamic(ctx context.Context, Req *api.SpacePushDynamicReq) (r *api.SpacePushDynamicReply, err error) {
	var _args PushDynamicArgs
	_args.Req = Req
	var _result PushDynamicResult
	if err = p.c.Call(ctx, "PushDynamic", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
