// Code generated by Kitex v0.11.3. DO NOT EDIT.

package consumer

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	"github.com/liuhua1307/ImGo/rpc/dynamics/dynamic_consumer/kitex_gen/api"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	PushDynamic(ctx context.Context, Req *api.ConsumerPushDynamicReq, callOptions ...callopt.Option) (r *api.ConsumerPushDynamicReply, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kConsumerClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kConsumerClient struct {
	*kClient
}

func (p *kConsumerClient) PushDynamic(ctx context.Context, Req *api.ConsumerPushDynamicReq, callOptions ...callopt.Option) (r *api.ConsumerPushDynamicReply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.PushDynamic(ctx, Req)
}
