// Code generated by Kitex v0.11.3. DO NOT EDIT.

package consumer

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	"github.com/liuhua1307/ImGo/rpc/dynamics/dynamic_consumer/kitex_gen/api"
	proto "google.golang.org/protobuf/proto"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"PushDynamic": kitex.NewMethodInfo(
		pushDynamicHandler,
		newPushDynamicArgs,
		newPushDynamicResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingUnary),
	),
}

var (
	consumerServiceInfo                = NewServiceInfo()
	consumerServiceInfoForClient       = NewServiceInfoForClient()
	consumerServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return consumerServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return consumerServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return consumerServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "Consumer"
	handlerType := (*api.Consumer)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "DynamicConsumer",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.11.3",
		Extra:           extra,
	}
	return svcInfo
}

func pushDynamicHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(api.ConsumerPushDynamicReq)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(api.Consumer).PushDynamic(ctx, req)
		if err != nil {
			return err
		}
		return st.SendMsg(resp)
	case *PushDynamicArgs:
		success, err := handler.(api.Consumer).PushDynamic(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*PushDynamicResult)
		realResult.Success = success
		return nil
	default:
		return errInvalidMessageType
	}
}
func newPushDynamicArgs() interface{} {
	return &PushDynamicArgs{}
}

func newPushDynamicResult() interface{} {
	return &PushDynamicResult{}
}

type PushDynamicArgs struct {
	Req *api.ConsumerPushDynamicReq
}

func (p *PushDynamicArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(api.ConsumerPushDynamicReq)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *PushDynamicArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *PushDynamicArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *PushDynamicArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, nil
	}
	return proto.Marshal(p.Req)
}

func (p *PushDynamicArgs) Unmarshal(in []byte) error {
	msg := new(api.ConsumerPushDynamicReq)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var PushDynamicArgs_Req_DEFAULT *api.ConsumerPushDynamicReq

func (p *PushDynamicArgs) GetReq() *api.ConsumerPushDynamicReq {
	if !p.IsSetReq() {
		return PushDynamicArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *PushDynamicArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *PushDynamicArgs) GetFirstArgument() interface{} {
	return p.Req
}

type PushDynamicResult struct {
	Success *api.ConsumerPushDynamicReply
}

var PushDynamicResult_Success_DEFAULT *api.ConsumerPushDynamicReply

func (p *PushDynamicResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(api.ConsumerPushDynamicReply)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *PushDynamicResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *PushDynamicResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *PushDynamicResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, nil
	}
	return proto.Marshal(p.Success)
}

func (p *PushDynamicResult) Unmarshal(in []byte) error {
	msg := new(api.ConsumerPushDynamicReply)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *PushDynamicResult) GetSuccess() *api.ConsumerPushDynamicReply {
	if !p.IsSetSuccess() {
		return PushDynamicResult_Success_DEFAULT
	}
	return p.Success
}

func (p *PushDynamicResult) SetSuccess(x interface{}) {
	p.Success = x.(*api.ConsumerPushDynamicReply)
}

func (p *PushDynamicResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *PushDynamicResult) GetResult() interface{} {
	return p.Success
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) PushDynamic(ctx context.Context, Req *api.ConsumerPushDynamicReq) (r *api.ConsumerPushDynamicReply, err error) {
	var _args PushDynamicArgs
	_args.Req = Req
	var _result PushDynamicResult
	if err = p.c.Call(ctx, "PushDynamic", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
