// Code generated by Fastpb v0.0.2. DO NOT EDIT.

package api

import (
	fmt "fmt"
	fastpb "github.com/cloudwego/fastpb"
)

var (
	_ = fmt.Errorf
	_ = fastpb.Skip
)

func (x *SmsGetCodeReq) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_SmsGetCodeReq[number], err)
}

func (x *SmsGetCodeReq) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.PhoneNumber, offset, err = fastpb.ReadString(buf, _type)
	return offset, err
}

func (x *SmsGetCodeReply) FastRead(buf []byte, _type int8, number int32) (offset int, err error) {
	switch number {
	case 1:
		offset, err = x.fastReadField1(buf, _type)
		if err != nil {
			goto ReadFieldError
		}
	default:
		offset, err = fastpb.Skip(buf, _type, number)
		if err != nil {
			goto SkipFieldError
		}
	}
	return offset, nil
SkipFieldError:
	return offset, fmt.Errorf("%T cannot parse invalid wire-format data, error: %s", x, err)
ReadFieldError:
	return offset, fmt.Errorf("%T read field %d '%s' error: %s", x, number, fieldIDToName_SmsGetCodeReply[number], err)
}

func (x *SmsGetCodeReply) fastReadField1(buf []byte, _type int8) (offset int, err error) {
	x.SmsCodeId, offset, err = fastpb.ReadUint32(buf, _type)
	return offset, err
}

func (x *SmsGetCodeReq) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *SmsGetCodeReq) fastWriteField1(buf []byte) (offset int) {
	if x.PhoneNumber == "" {
		return offset
	}
	offset += fastpb.WriteString(buf[offset:], 1, x.GetPhoneNumber())
	return offset
}

func (x *SmsGetCodeReply) FastWrite(buf []byte) (offset int) {
	if x == nil {
		return offset
	}
	offset += x.fastWriteField1(buf[offset:])
	return offset
}

func (x *SmsGetCodeReply) fastWriteField1(buf []byte) (offset int) {
	if x.SmsCodeId == 0 {
		return offset
	}
	offset += fastpb.WriteUint32(buf[offset:], 1, x.GetSmsCodeId())
	return offset
}

func (x *SmsGetCodeReq) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *SmsGetCodeReq) sizeField1() (n int) {
	if x.PhoneNumber == "" {
		return n
	}
	n += fastpb.SizeString(1, x.GetPhoneNumber())
	return n
}

func (x *SmsGetCodeReply) Size() (n int) {
	if x == nil {
		return n
	}
	n += x.sizeField1()
	return n
}

func (x *SmsGetCodeReply) sizeField1() (n int) {
	if x.SmsCodeId == 0 {
		return n
	}
	n += fastpb.SizeUint32(1, x.GetSmsCodeId())
	return n
}

var fieldIDToName_SmsGetCodeReq = map[int32]string{
	1: "PhoneNumber",
}

var fieldIDToName_SmsGetCodeReply = map[int32]string{
	1: "SmsCodeId",
}
