// Code generated by Kitex v0.10.3. DO NOT EDIT.

package chat

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	api "github.com/liuhua1307/ImGo/rpc/chat/kitex_gen/api"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Send(ctx context.Context, Req *api.ChatSendReq, callOptions ...callopt.Option) (r *api.ChatSendReply, err error)
	GetMessageList(ctx context.Context, Req *api.ChatGetMessageListReq, callOptions ...callopt.Option) (r *api.ChatGetMessageListReply, err error)
}

// NewClient creates a client for the domain defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kChatClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the domain defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kChatClient struct {
	*kClient
}

func (p *kChatClient) Send(ctx context.Context, Req *api.ChatSendReq, callOptions ...callopt.Option) (r *api.ChatSendReply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Send(ctx, Req)
}

func (p *kChatClient) GetMessageList(ctx context.Context, Req *api.ChatGetMessageListReq, callOptions ...callopt.Option) (r *api.ChatGetMessageListReply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetMessageList(ctx, Req)
}
