// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/cloudwego/kitex/server"
	"github.com/liuhua1307/ImGo/rpc/space/configs"
	cache2 "github.com/liuhua1307/ImGo/rpc/space/dynamics/cache"
	"github.com/liuhua1307/ImGo/rpc/space/dynamics/repository"
	"github.com/liuhua1307/ImGo/rpc/space/dynamics/usecase"
	"github.com/liuhua1307/ImGo/rpc/space/pkg/cache"
	server2 "github.com/liuhua1307/ImGo/rpc/space/server"
)

// Injectors from wire.go:

func wireApp() server.Server {
	context := configs.NewContext()
	client := configs.NewRDB(context)
	redisCache := cache.NewRedis(client)
	db := configs.DB(context)
	dynamicsMYSQLRepository := repository.NewDynamicsMYSQLRepository(db)
	dynamicsRedisRepository := cache2.NewDynamicsRepository(redisCache, dynamicsMYSQLRepository)
	dynamicUseCase := usecase.NewDynamicsUseCase(dynamicsRedisRepository)
	space := server2.NewSpaceImpl(dynamicUseCase)
	serverServer := server2.NewKitexServer(space)
	return serverServer
}
